// Função para validar se o valor é um número
function validarNumero(valor) {
  return !isNaN(valor) && valor !== "";
}

// Função para somar dois números
function somar(a, b) {
  return a + b;
}

// Função para subtrair dois números
function subtrair(a, b) {
  return a - b;
}

// Função para multiplicar dois números
function multiplicar(a, b) {
  return a * b;
}

// Função para dividir dois números
function dividir(a, b) {
  // Verificar se o divisor é zero
  if (b === 0) {
    alert("Erro: Não é possível dividir por zero.");
    return null;
  }
  return a / b;
}

// Função principal que executa o fluxo da calculadora
function calculadora() {
  // Pedir ao usuário os dois números
  let numero1 = prompt("Digite o primeiro número:");
  let numero2 = prompt("Digite o segundo número:");

  // Validar se ambos os valores são números
  if (!validarNumero(numero1) || !validarNumero(numero2)) {
    alert("Por favor, insira valores válidos.");
    return;
  }

  // Converter os números de string para número
  numero1 = parseFloat(numero1);
  numero2 = parseFloat(numero2);

  // Pedir ao usuário a operação desejada
  let operacao = prompt("Escolha uma operação: soma, subtração, multiplicação ou divisão").toLowerCase();

  // Variável para armazenar o resultado
  let resultado;

  // Realizar a operação escolhida
  switch (operacao) {
    case "soma":
      resultado = somar(numero1, numero2);
      break;
    case "subtração":
      resultado = subtrair(numero1, numero2);
      break;
    case "multiplicação":
      resultado = multiplicar(numero1, numero2);
      break;
    case "divisão":
      resultado = dividir(numero1, numero2);
      break;
    default:
      alert("Operação inválida.");
      return;
  }

  // Exibir o resultado
  if (resultado !== null) {
    alert("O resultado da operação é: " + resultado);
  }
}

// Chamar a função da calculadora
calculadora();
